spring:
  application:
    name: twitterlike

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password

  datasource:
    url: jdbc:sqlite:./.local/data/twitterlike.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    job:
      enabled: false

  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
